// Copyright 2026 The mitmproxy-go Authors.
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: mitmproxy_ipc.proto

package local

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Packet with associated tunnel info (Windows pipe to mitmproxy)
type PacketWithMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	TunnelInfo    *TunnelInfo            `protobuf:"bytes,2,opt,name=tunnel_info,json=tunnelInfo,proto3" json:"tunnel_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketWithMeta) Reset() {
	*x = PacketWithMeta{}
	mi := &file_mitmproxy_ipc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketWithMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketWithMeta) ProtoMessage() {}

func (x *PacketWithMeta) ProtoReflect() protoreflect.Message {
	mi := &file_mitmproxy_ipc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketWithMeta.ProtoReflect.Descriptor instead.
func (*PacketWithMeta) Descriptor() ([]byte, []int) {
	return file_mitmproxy_ipc_proto_rawDescGZIP(), []int{0}
}

func (x *PacketWithMeta) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PacketWithMeta) GetTunnelInfo() *TunnelInfo {
	if x != nil {
		return x.TunnelInfo
	}
	return nil
}

type TunnelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           *uint32                `protobuf:"varint,1,opt,name=pid,proto3,oneof" json:"pid,omitempty"`
	ProcessName   *string                `protobuf:"bytes,2,opt,name=process_name,json=processName,proto3,oneof" json:"process_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelInfo) Reset() {
	*x = TunnelInfo{}
	mi := &file_mitmproxy_ipc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelInfo) ProtoMessage() {}

func (x *TunnelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mitmproxy_ipc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelInfo.ProtoReflect.Descriptor instead.
func (*TunnelInfo) Descriptor() ([]byte, []int) {
	return file_mitmproxy_ipc_proto_rawDescGZIP(), []int{1}
}

func (x *TunnelInfo) GetPid() uint32 {
	if x != nil && x.Pid != nil {
		return *x.Pid
	}
	return 0
}

func (x *TunnelInfo) GetProcessName() string {
	if x != nil && x.ProcessName != nil {
		return *x.ProcessName
	}
	return ""
}

// Packet or intercept spec (Windows pipe to redirector)
type FromProxy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*FromProxy_Packet
	//	*FromProxy_InterceptConf
	Message       isFromProxy_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FromProxy) Reset() {
	*x = FromProxy{}
	mi := &file_mitmproxy_ipc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromProxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromProxy) ProtoMessage() {}

func (x *FromProxy) ProtoReflect() protoreflect.Message {
	mi := &file_mitmproxy_ipc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromProxy.ProtoReflect.Descriptor instead.
func (*FromProxy) Descriptor() ([]byte, []int) {
	return file_mitmproxy_ipc_proto_rawDescGZIP(), []int{2}
}

func (x *FromProxy) GetMessage() isFromProxy_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *FromProxy) GetPacket() *Packet {
	if x != nil {
		if x, ok := x.Message.(*FromProxy_Packet); ok {
			return x.Packet
		}
	}
	return nil
}

func (x *FromProxy) GetInterceptConf() *InterceptConf {
	if x != nil {
		if x, ok := x.Message.(*FromProxy_InterceptConf); ok {
			return x.InterceptConf
		}
	}
	return nil
}

type isFromProxy_Message interface {
	isFromProxy_Message()
}

type FromProxy_Packet struct {
	Packet *Packet `protobuf:"bytes,1,opt,name=packet,proto3,oneof"`
}

type FromProxy_InterceptConf struct {
	InterceptConf *InterceptConf `protobuf:"bytes,2,opt,name=intercept_conf,json=interceptConf,proto3,oneof"`
}

func (*FromProxy_Packet) isFromProxy_Message() {}

func (*FromProxy_InterceptConf) isFromProxy_Message() {}

// Packet (macOS UDP Stream)
// ⚠️ Bump network extension version on changes, https://github.com/mitmproxy/mitmproxy_rs/pull/227.
type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_mitmproxy_ipc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_mitmproxy_ipc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_mitmproxy_ipc_proto_rawDescGZIP(), []int{3}
}

func (x *Packet) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Intercept conf (macOS Control Stream)
// ⚠️ Bump network extension version on changes, https://github.com/mitmproxy/mitmproxy_rs/pull/227.
type InterceptConf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []string               `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterceptConf) Reset() {
	*x = InterceptConf{}
	mi := &file_mitmproxy_ipc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterceptConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterceptConf) ProtoMessage() {}

func (x *InterceptConf) ProtoReflect() protoreflect.Message {
	mi := &file_mitmproxy_ipc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterceptConf.ProtoReflect.Descriptor instead.
func (*InterceptConf) Descriptor() ([]byte, []int) {
	return file_mitmproxy_ipc_proto_rawDescGZIP(), []int{4}
}

func (x *InterceptConf) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

// New flow (macOS TCP/UDP Stream)
// ⚠️ Bump network extension version on changes, https://github.com/mitmproxy/mitmproxy_rs/pull/227.
type NewFlow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*NewFlow_Tcp
	//	*NewFlow_Udp
	Message       isNewFlow_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewFlow) Reset() {
	*x = NewFlow{}
	mi := &file_mitmproxy_ipc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewFlow) ProtoMessage() {}

func (x *NewFlow) ProtoReflect() protoreflect.Message {
	mi := &file_mitmproxy_ipc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewFlow.ProtoReflect.Descriptor instead.
func (*NewFlow) Descriptor() ([]byte, []int) {
	return file_mitmproxy_ipc_proto_rawDescGZIP(), []int{5}
}

func (x *NewFlow) GetMessage() isNewFlow_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *NewFlow) GetTcp() *TcpFlow {
	if x != nil {
		if x, ok := x.Message.(*NewFlow_Tcp); ok {
			return x.Tcp
		}
	}
	return nil
}

func (x *NewFlow) GetUdp() *UdpFlow {
	if x != nil {
		if x, ok := x.Message.(*NewFlow_Udp); ok {
			return x.Udp
		}
	}
	return nil
}

type isNewFlow_Message interface {
	isNewFlow_Message()
}

type NewFlow_Tcp struct {
	Tcp *TcpFlow `protobuf:"bytes,1,opt,name=tcp,proto3,oneof"`
}

type NewFlow_Udp struct {
	Udp *UdpFlow `protobuf:"bytes,2,opt,name=udp,proto3,oneof"`
}

func (*NewFlow_Tcp) isNewFlow_Message() {}

func (*NewFlow_Udp) isNewFlow_Message() {}

// ⚠️ Bump network extension version on changes, https://github.com/mitmproxy/mitmproxy_rs/pull/227.
type TcpFlow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemoteAddress *Address               `protobuf:"bytes,1,opt,name=remote_address,json=remoteAddress,proto3" json:"remote_address,omitempty"`
	TunnelInfo    *TunnelInfo            `protobuf:"bytes,2,opt,name=tunnel_info,json=tunnelInfo,proto3" json:"tunnel_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpFlow) Reset() {
	*x = TcpFlow{}
	mi := &file_mitmproxy_ipc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpFlow) ProtoMessage() {}

func (x *TcpFlow) ProtoReflect() protoreflect.Message {
	mi := &file_mitmproxy_ipc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpFlow.ProtoReflect.Descriptor instead.
func (*TcpFlow) Descriptor() ([]byte, []int) {
	return file_mitmproxy_ipc_proto_rawDescGZIP(), []int{6}
}

func (x *TcpFlow) GetRemoteAddress() *Address {
	if x != nil {
		return x.RemoteAddress
	}
	return nil
}

func (x *TcpFlow) GetTunnelInfo() *TunnelInfo {
	if x != nil {
		return x.TunnelInfo
	}
	return nil
}

// ⚠️ Bump network extension version on changes, https://github.com/mitmproxy/mitmproxy_rs/pull/227.
type UdpFlow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalAddress  *Address               `protobuf:"bytes,1,opt,name=local_address,json=localAddress,proto3,oneof" json:"local_address,omitempty"`
	TunnelInfo    *TunnelInfo            `protobuf:"bytes,3,opt,name=tunnel_info,json=tunnelInfo,proto3" json:"tunnel_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UdpFlow) Reset() {
	*x = UdpFlow{}
	mi := &file_mitmproxy_ipc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UdpFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UdpFlow) ProtoMessage() {}

func (x *UdpFlow) ProtoReflect() protoreflect.Message {
	mi := &file_mitmproxy_ipc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UdpFlow.ProtoReflect.Descriptor instead.
func (*UdpFlow) Descriptor() ([]byte, []int) {
	return file_mitmproxy_ipc_proto_rawDescGZIP(), []int{7}
}

func (x *UdpFlow) GetLocalAddress() *Address {
	if x != nil {
		return x.LocalAddress
	}
	return nil
}

func (x *UdpFlow) GetTunnelInfo() *TunnelInfo {
	if x != nil {
		return x.TunnelInfo
	}
	return nil
}

type UdpPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	RemoteAddress *Address               `protobuf:"bytes,2,opt,name=remote_address,json=remoteAddress,proto3" json:"remote_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UdpPacket) Reset() {
	*x = UdpPacket{}
	mi := &file_mitmproxy_ipc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UdpPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UdpPacket) ProtoMessage() {}

func (x *UdpPacket) ProtoReflect() protoreflect.Message {
	mi := &file_mitmproxy_ipc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UdpPacket.ProtoReflect.Descriptor instead.
func (*UdpPacket) Descriptor() ([]byte, []int) {
	return file_mitmproxy_ipc_proto_rawDescGZIP(), []int{8}
}

func (x *UdpPacket) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UdpPacket) GetRemoteAddress() *Address {
	if x != nil {
		return x.RemoteAddress
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_mitmproxy_ipc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_mitmproxy_ipc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_mitmproxy_ipc_proto_rawDescGZIP(), []int{9}
}

func (x *Address) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Address) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_mitmproxy_ipc_proto protoreflect.FileDescriptor

const file_mitmproxy_ipc_proto_rawDesc = "" +
	"\n" +
	"\x13mitmproxy_ipc.proto\x12\rmitmproxy_ipc\"`\n" +
	"\x0ePacketWithMeta\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12:\n" +
	"\vtunnel_info\x18\x02 \x01(\v2\x19.mitmproxy_ipc.TunnelInfoR\n" +
	"tunnelInfo\"d\n" +
	"\n" +
	"TunnelInfo\x12\x15\n" +
	"\x03pid\x18\x01 \x01(\rH\x00R\x03pid\x88\x01\x01\x12&\n" +
	"\fprocess_name\x18\x02 \x01(\tH\x01R\vprocessName\x88\x01\x01B\x06\n" +
	"\x04_pidB\x0f\n" +
	"\r_process_name\"\x8e\x01\n" +
	"\tFromProxy\x12/\n" +
	"\x06packet\x18\x01 \x01(\v2\x15.mitmproxy_ipc.PacketH\x00R\x06packet\x12E\n" +
	"\x0eintercept_conf\x18\x02 \x01(\v2\x1c.mitmproxy_ipc.InterceptConfH\x00R\rinterceptConfB\t\n" +
	"\amessage\"\x1c\n" +
	"\x06Packet\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\")\n" +
	"\rInterceptConf\x12\x18\n" +
	"\aactions\x18\x01 \x03(\tR\aactions\"l\n" +
	"\aNewFlow\x12*\n" +
	"\x03tcp\x18\x01 \x01(\v2\x16.mitmproxy_ipc.TcpFlowH\x00R\x03tcp\x12*\n" +
	"\x03udp\x18\x02 \x01(\v2\x16.mitmproxy_ipc.UdpFlowH\x00R\x03udpB\t\n" +
	"\amessage\"\x84\x01\n" +
	"\aTcpFlow\x12=\n" +
	"\x0eremote_address\x18\x01 \x01(\v2\x16.mitmproxy_ipc.AddressR\rremoteAddress\x12:\n" +
	"\vtunnel_info\x18\x02 \x01(\v2\x19.mitmproxy_ipc.TunnelInfoR\n" +
	"tunnelInfo\"\x99\x01\n" +
	"\aUdpFlow\x12@\n" +
	"\rlocal_address\x18\x01 \x01(\v2\x16.mitmproxy_ipc.AddressH\x00R\flocalAddress\x88\x01\x01\x12:\n" +
	"\vtunnel_info\x18\x03 \x01(\v2\x19.mitmproxy_ipc.TunnelInfoR\n" +
	"tunnelInfoB\x10\n" +
	"\x0e_local_address\"^\n" +
	"\tUdpPacket\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12=\n" +
	"\x0eremote_address\x18\x02 \x01(\v2\x16.mitmproxy_ipc.AddressR\rremoteAddress\"1\n" +
	"\aAddress\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04portb\x06proto3"

var (
	file_mitmproxy_ipc_proto_rawDescOnce sync.Once
	file_mitmproxy_ipc_proto_rawDescData []byte
)

func file_mitmproxy_ipc_proto_rawDescGZIP() []byte {
	file_mitmproxy_ipc_proto_rawDescOnce.Do(func() {
		file_mitmproxy_ipc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mitmproxy_ipc_proto_rawDesc), len(file_mitmproxy_ipc_proto_rawDesc)))
	})
	return file_mitmproxy_ipc_proto_rawDescData
}

var file_mitmproxy_ipc_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_mitmproxy_ipc_proto_goTypes = []any{
	(*PacketWithMeta)(nil), // 0: mitmproxy_ipc.PacketWithMeta
	(*TunnelInfo)(nil),     // 1: mitmproxy_ipc.TunnelInfo
	(*FromProxy)(nil),      // 2: mitmproxy_ipc.FromProxy
	(*Packet)(nil),         // 3: mitmproxy_ipc.Packet
	(*InterceptConf)(nil),  // 4: mitmproxy_ipc.InterceptConf
	(*NewFlow)(nil),        // 5: mitmproxy_ipc.NewFlow
	(*TcpFlow)(nil),        // 6: mitmproxy_ipc.TcpFlow
	(*UdpFlow)(nil),        // 7: mitmproxy_ipc.UdpFlow
	(*UdpPacket)(nil),      // 8: mitmproxy_ipc.UdpPacket
	(*Address)(nil),        // 9: mitmproxy_ipc.Address
}
var file_mitmproxy_ipc_proto_depIdxs = []int32{
	1,  // 0: mitmproxy_ipc.PacketWithMeta.tunnel_info:type_name -> mitmproxy_ipc.TunnelInfo
	3,  // 1: mitmproxy_ipc.FromProxy.packet:type_name -> mitmproxy_ipc.Packet
	4,  // 2: mitmproxy_ipc.FromProxy.intercept_conf:type_name -> mitmproxy_ipc.InterceptConf
	6,  // 3: mitmproxy_ipc.NewFlow.tcp:type_name -> mitmproxy_ipc.TcpFlow
	7,  // 4: mitmproxy_ipc.NewFlow.udp:type_name -> mitmproxy_ipc.UdpFlow
	9,  // 5: mitmproxy_ipc.TcpFlow.remote_address:type_name -> mitmproxy_ipc.Address
	1,  // 6: mitmproxy_ipc.TcpFlow.tunnel_info:type_name -> mitmproxy_ipc.TunnelInfo
	9,  // 7: mitmproxy_ipc.UdpFlow.local_address:type_name -> mitmproxy_ipc.Address
	1,  // 8: mitmproxy_ipc.UdpFlow.tunnel_info:type_name -> mitmproxy_ipc.TunnelInfo
	9,  // 9: mitmproxy_ipc.UdpPacket.remote_address:type_name -> mitmproxy_ipc.Address
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_mitmproxy_ipc_proto_init() }
func file_mitmproxy_ipc_proto_init() {
	if File_mitmproxy_ipc_proto != nil {
		return
	}
	file_mitmproxy_ipc_proto_msgTypes[1].OneofWrappers = []any{}
	file_mitmproxy_ipc_proto_msgTypes[2].OneofWrappers = []any{
		(*FromProxy_Packet)(nil),
		(*FromProxy_InterceptConf)(nil),
	}
	file_mitmproxy_ipc_proto_msgTypes[5].OneofWrappers = []any{
		(*NewFlow_Tcp)(nil),
		(*NewFlow_Udp)(nil),
	}
	file_mitmproxy_ipc_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mitmproxy_ipc_proto_rawDesc), len(file_mitmproxy_ipc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mitmproxy_ipc_proto_goTypes,
		DependencyIndexes: file_mitmproxy_ipc_proto_depIdxs,
		MessageInfos:      file_mitmproxy_ipc_proto_msgTypes,
	}.Build()
	File_mitmproxy_ipc_proto = out.File
	file_mitmproxy_ipc_proto_goTypes = nil
	file_mitmproxy_ipc_proto_depIdxs = nil
}
