// Copyright 2026 The mitmproxy-go Authors.
// SPDX-License-Identifier: MIT

package certs

import (
	"crypto"
	"encoding/binary"
	"maps"
	"slices"
	"strings"
	"sync"
)

// Entry is one certificate the store can serve: the leaf, the private
// key it is served with, and the chain sent after it. ChainFile is the
// path the chain was read from, or "" when the chain is the store's
// default CA alone. An Entry and its certificates must not be modified
// after being added to or returned by a Store.
type Entry struct {
	Cert       *Cert
	PrivateKey crypto.Signer
	ChainFile  string
	ChainCerts []*Cert
}

// storeCap is how many generated entries a [Store] keeps before the
// oldest is expired. Each store copies it into an unexported field, so a
// test can lower its own store's cap.
const storeCap = 100

// Store is an in-memory certificate store. [Store.GetCert] serves a
// certificate for a requested name, generating one with [DummyCert]
// under the store's CA when neither a configured certificate nor an
// already generated one matches; generated entries are kept up to a cap
// of 100 and then expired first-in first-out.
//
// A Store synchronises itself: all methods are safe for concurrent use.
// The mutex is held across certificate generation, so two requests for
// the same new name wait for one generation.
type Store struct {
	defaultPrivateKey crypto.Signer
	defaultCA         *Cert
	defaultChainFile  string
	defaultChainCerts []*Cert
	defaultCRL        []byte

	mu          sync.Mutex
	configured  map[string]*Entry
	generated   map[generatedCertID]*Entry
	expireQueue []*Entry
	cap         int
}

type generatedCertID struct {
	commonName string
	sans       string
}

// GetCert selects a configured certificate or generates a leaf under the CA.
// Lookup tries the CN's exact and successively broader wildcard forms, then
// each SAN in order (wildcard expansion applies only to DNS SANs), then "*",
// and finally the generated cache. Generated identity is CN plus SANs in order;
// organization and crlURL are excluded, so the first generation's values win.
// The cache keeps 100 generated entries in FIFO order; hits do not refresh
// entries, and eviction removes every mapping pointing to the expired entry.
// Names must be plain-ASCII, IDNA-encoded where applicable. Generation errors
// are returned without changing the cache.
func (s *Store) GetCert(commonName string, sans []GeneralName, organization, crlURL string) (*Entry, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	if commonName != "" {
		if entry := s.lookupName(commonName, true); entry != nil {
			return entry, nil
		}
	}
	for _, name := range sans {
		if entry := s.lookupName(name.String(), name.Type() == GeneralNameDNS); entry != nil {
			return entry, nil
		}
	}
	if entry := s.configured["*"]; entry != nil {
		return entry, nil
	}

	// Length-prefix each typed name so delimiters inside values cannot collide.
	var encoded []byte
	for _, name := range sans {
		value := name.String()
		encoded = binary.AppendUvarint(encoded, uint64(name.Type()))
		encoded = binary.AppendUvarint(encoded, uint64(len(value)))
		encoded = append(encoded, value...)
	}
	id := generatedCertID{commonName: commonName, sans: string(encoded)}
	if entry := s.generated[id]; entry != nil {
		return entry, nil
	}
	cert, err := DummyCert(s.defaultPrivateKey, s.defaultCA, commonName, sans, organization, crlURL)
	if err != nil {
		return nil, err
	}
	entry := &Entry{Cert: cert, PrivateKey: s.defaultPrivateKey, ChainFile: s.defaultChainFile, ChainCerts: slices.Clone(s.defaultChainCerts)}
	if s.generated == nil {
		s.generated = make(map[generatedCertID]*Entry)
	}
	s.generated[id] = entry
	s.expireQueue = append(s.expireQueue, entry)
	if len(s.expireQueue) > s.cap {
		expired := s.expireQueue[0]
		s.expireQueue = slices.Delete(s.expireQueue, 0, 1)
		maps.DeleteFunc(s.configured, func(_ string, value *Entry) bool { return value == expired })
		maps.DeleteFunc(s.generated, func(_ generatedCertID, value *Entry) bool { return value == expired })
	}
	return entry, nil
}

// lookupName is called with mu held. Wildcards include every parent suffix,
// even a top-level suffix, matching mitmproxy's configured-certificate lookup.
func (s *Store) lookupName(name string, wildcard bool) *Entry {
	if entry := s.configured[name]; entry != nil {
		return entry
	}
	if wildcard {
		for {
			_, suffix, ok := strings.Cut(name, ".")
			if !ok {
				break
			}
			if entry := s.configured["*."+suffix]; entry != nil {
				return entry
			}
			name = suffix
		}
	}
	return nil
}

// AddCert registers entry under its nonempty CN, every SAN's textual value,
// and names. Later additions replace earlier mappings for the same name.
// Configured entries are not subject to the generated-entry FIFO unless entry
// itself was generated by this Store. The caller must not modify entry later.
func (s *Store) AddCert(entry *Entry, names ...string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.configured == nil {
		s.configured = make(map[string]*Entry)
	}
	if name := entry.Cert.CN(); name != "" {
		s.configured[name] = entry
	}
	for _, name := range entry.Cert.AltNames() {
		s.configured[name.String()] = entry
	}
	for _, name := range names {
		s.configured[name] = entry
	}
}

// DefaultCA returns the store's CA certificate.
func (s *Store) DefaultCA() *Cert {
	return s.defaultCA
}

// DefaultPrivateKey returns the CA private key, which also signs every
// generated leaf.
func (s *Store) DefaultPrivateKey() crypto.Signer {
	return s.defaultPrivateKey
}

// DefaultChainFile returns the path of the PEM file whose certificates
// are sent as the default chain, or "" when the store was loaded from a
// file holding only the CA certificate.
func (s *Store) DefaultChainFile() string {
	return s.defaultChainFile
}

// DefaultChainCerts returns the certificates of the default chain: the
// certificates of [Store.DefaultChainFile], or the CA alone.
func (s *Store) DefaultChainCerts() []*Cert {
	return slices.Clone(s.defaultChainCerts)
}

// DefaultCRL returns the DER-encoded empty certificate revocation list
// signed by the CA, which the proxy serves at the CRL distribution point
// of its generated leaves.
func (s *Store) DefaultCRL() []byte {
	return slices.Clone(s.defaultCRL)
}
