// Copyright 2026 The mitmproxy-go Authors.
// SPDX-License-Identifier: MIT

package httplayer

import (
	"bytes"
	"errors"
	"io"
	"testing"

	gocmp "github.com/google/go-cmp/cmp"
	"github.com/quic-go/qpack"

	"github.com/zchee/mitmproxy-go/flow"
	"github.com/zchee/mitmproxy-go/internal/h3"
)

func readHTTP3TestMessage(t *testing.T, reader io.Reader) ([]qpack.HeaderField, []byte, []qpack.HeaderField) {
	t.Helper()
	headers := readHTTP3TestHeaders(t, reader)
	var body []byte
	var trailers []qpack.HeaderField
	for {
		var first [1]byte
		_, err := io.ReadFull(reader, first[:])
		if errors.Is(err, io.EOF) {
			return headers, body, trailers
		}
		if err != nil {
			t.Fatal(err)
		}
		// Every frame generated by these peers has a one-byte frame type.
		framed := io.MultiReader(bytes.NewReader(first[:]), reader)
		if first[0] == 1 {
			trailers = readHTTP3TestHeaders(t, framed)
			continue
		}
		kind, payload := readHTTP3TestFrame(t, framed)
		if kind != 0 {
			t.Fatalf("message frame = %d, want DATA or trailers", kind)
		}
		body = append(body, payload...)
	}
}

func TestHTTP3DriverTrailers(t *testing.T) {
	// py:test/mitmproxy/proxy/layers/http/test_http3.py:test_simple,
	// test_request_trailers and test_response_trailers (both stream variants).
	tests := map[string]struct {
		stream bool
	}{"buffered": {}, "streamed": {stream: true}}
	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			ctx := http3TestContext(t)
			addon := &streamAddon{edit: func(name string, f *flow.HTTPFlow) {
				switch name {
				case "requestheaders":
					f.Request.Stream = test.stream
				case "responseheaders":
					f.Response.Stream = test.stream
				case "request":
					f.Request.Trailers.Del("req-trailer-a")
				case "response":
					f.Response.Trailers.Del("resp-trailer-a")
				}
			}}
			stream, _ := newTestStream(t, addon)
			peer, source := newHTTP3TestPeer(t, ctx, false)
			origin, destination := newHTTP3TestPeer(t, ctx, true)
			clientWire, err := peer.conn.OpenStreamSync(ctx)
			if err != nil {
				t.Fatal(err)
			}
			requestFields := []qpack.HeaderField{{Name: ":method", Value: "POST"}, {Name: ":scheme", Value: "https"}, {Name: ":path", Value: "/"}, {Name: ":authority", Value: "example.com"}, {Name: "x-foo", Value: "1"}, {Name: "x-bar", Value: "2"}, {Name: "x-foo", Value: "3"}}
			writeHTTP3TestHeaders(t, clientWire, requestFields)
			head, err := source.Receive(ctx)
			if err != nil {
				t.Fatal(err)
			}
			originID, err := destination.OpenStream(ctx)
			if err != nil {
				t.Fatal(err)
			}
			client := &http3Server{engine: source, identity: head.Identity, failureDone: source.StreamFailed(head.Identity), id: stream.id, normalize: true, head: &head}
			server := &http3Client{engine: destination, identity: originID, failureDone: destination.StreamFailed(originID), id: stream.id, normalize: true}
			done := make(chan error, 1)
			go func() { done <- (&streamDriver{stream: stream, client: client, server: server}).run(ctx) }()
			writeHTTP3TestFrame(t, clientWire, 0, []byte("Hello World!"))
			writeHTTP3TestHeaders(t, clientWire, []qpack.HeaderField{{Name: "req-trailer-a", Value: "a"}, {Name: "req-trailer-b", Value: "b"}})
			if err := clientWire.Close(); err != nil {
				t.Fatal(err)
			}
			originWire, err := origin.conn.AcceptStream(ctx)
			if err != nil {
				t.Fatal(err)
			}
			fields, body, trailers := readHTTP3TestMessage(t, originWire)
			if diff := gocmp.Diff(requestFields, fields); diff != "" {
				t.Fatalf("forwarded ordered fields (-want +got):\n%s", diff)
			}
			if diff := gocmp.Diff("Hello World!", string(body)); diff != "" {
				t.Fatal(diff)
			}
			if diff := gocmp.Diff([]qpack.HeaderField{{Name: "req-trailer-b", Value: "b"}}, trailers); diff != "" {
				t.Fatal(diff)
			}
			writeHTTP3TestHeaders(t, originWire, []qpack.HeaderField{{Name: ":status", Value: "103"}})
			writeHTTP3TestHeaders(t, originWire, []qpack.HeaderField{{Name: ":status", Value: "200"}})
			writeHTTP3TestFrame(t, originWire, 0, []byte("Hello, World!"))
			writeHTTP3TestHeaders(t, originWire, []qpack.HeaderField{{Name: "resp-trailer-a", Value: "a"}, {Name: "resp-trailer-b", Value: "b"}})
			if err := originWire.Close(); err != nil {
				t.Fatal(err)
			}
			fields, body, trailers = readHTTP3TestMessage(t, clientWire)
			if diff := gocmp.Diff([]qpack.HeaderField{{Name: ":status", Value: "200"}}, fields); diff != "" {
				t.Fatal(diff)
			}
			if diff := gocmp.Diff("Hello, World!", string(body)); diff != "" {
				t.Fatal(diff)
			}
			if diff := gocmp.Diff([]qpack.HeaderField{{Name: "resp-trailer-b", Value: "b"}}, trailers); diff != "" {
				t.Fatal(diff)
			}
			select {
			case err := <-done:
				if err != nil {
					t.Fatal(err)
				}
			case <-ctx.Done():
				t.Fatal(ctx.Err())
			}
			if diff := gocmp.Diff([]string{"requestheaders", "request", "responseheaders", "response"}, addon.calls); diff != "" {
				t.Fatalf("hook order (-want +got):\n%s", diff)
			}
			if stream.flow.Request.HTTPVersion != "HTTP/3" || stream.flow.Response.HTTPVersion != "HTTP/3" {
				t.Fatal("flow protocol version was lost")
			}
			if err := source.CancelStream(head.Identity, h3.ErrCodeRequestCancelled); err != nil {
				t.Fatal(err)
			}
		})
	}
}
